[package]
name = "raiti"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
iced = { git = "https://github.com/gintsgints/iced.git", features = ["debug", "canvas", "svg"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
